# Generator configuration

generator_version: "v1.0.0"
locale: "ja-JP"
memos:
  inbox_dir: "inputs/memos"
  trash_dir: "inputs/memos_trash"
  daily_target: 24
  research_keyword: "生成AI"
article:
  min_chars: 2500
  max_chars: 20000
  target_chars: 3200
  required_sections:
    - "背景と課題"
    - "結論（先出し）"
    - "手順"
    - "よくある失敗と対策"
    - "事例・効果"
    - "まとめ（CTA)"
    - "参考リンク"
  lead_min_chars: 100
  lead_max_chars: 220
  tone: "読者の実務課題に寄り添うプロの編集者視点で、落ち着いた敬体で執筆してください。"
images:
  enabled: true
  style: "clean-tech"
  internal_count: 2
  width: 1600
  height: 900
queue:
  out_dir: "articles-queue"
  posted_dir: "articles-posted"
assets_dir: "assets"
logs:
  dir: "logs"
concurrency:
  daily_limit: 10
  per_run_batch: 3
  max_parallel: 3
  jitter_sec:
    - 60
    - 420
dedupe:
  min_cosine_sim: 0.92
defaults:
  tags:
    - "Automation"
    - "AI"
    - "note"
  visibility: "public"
  series: "自動化で回すメディア運用"
  paid: false
  price: 500
  theme: "ビジネス"
retry:
  max_attempts: 3
  base_delay_sec: 20
  max_delay_sec: 90
quality_gate:
  ng_words:
    - "完全無料"
    - "必ず成功"
    - "絶対に稼げる"
  max_link_errors: 0
  reject_phrases:
    - "このセクションはドライラン"
    - "ダミー本文"
    - "テンプレートの長さを担保"
  min_body_lines: 40
  length_tolerance: 20000
note:
  visibility: "public"
  paid_enabled: false
  default_price: 500
  theme: "ビジネス"
  tone: "常に実務者の視点から課題→解決策→効果を論理的に語り、過剰な煽りや専門用語の乱用を避ける。"
